spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: test
      username: default

  # ??????????? ??????????? ? ???? ??????
  # ??? ??????? ? Docker ?????????? ?????????? ???? ?????? ?????????? ???????
  # docker run -itd -e POSTGRES_USER=test -e POSTGRES_PASSWORD=test -p 5432:5432 -v ./data:/var/lib/postgresql/data --name postgresql postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # URL ??
    username: test # ??? ???????????? ??? ??????? ???? ?????????? ????? ?????????? ? ???? ??????
    password: test # ?????? ????????????
    driver-class-name: org.postgresql.Driver # ??????? ??????? ????? ?????????????? ??? ???????????

  # ????????? ???????????? ????? ????? hibernate ????????????? ??? ?????? ??????????
  jpa:
    hibernate.ddl-auto: create-drop
  application:
    name:
      redis-lesson
